# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trade_operation_pb2 as trade__operation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trade_operation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeOperationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSystemInfo = channel.unary_unary(
                '/trade_operation.TradeOperation/SendSystemInfo',
                request_serializer=trade__operation__pb2.SystemInfoRequest.SerializeToString,
                response_deserializer=trade__operation__pb2.SystemInfoResponse.FromString,
                _registered_method=True)
        self.SendRefDataInfo = channel.unary_unary(
                '/trade_operation.TradeOperation/SendRefDataInfo',
                request_serializer=trade__operation__pb2.RefDataInfoRequest.SerializeToString,
                response_deserializer=trade__operation__pb2.RefDataInfoResponse.FromString,
                _registered_method=True)


class TradeOperationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSystemInfo(self, request, context):
        """Send operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRefDataInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeOperationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSystemInfo,
                    request_deserializer=trade__operation__pb2.SystemInfoRequest.FromString,
                    response_serializer=trade__operation__pb2.SystemInfoResponse.SerializeToString,
            ),
            'SendRefDataInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRefDataInfo,
                    request_deserializer=trade__operation__pb2.RefDataInfoRequest.FromString,
                    response_serializer=trade__operation__pb2.RefDataInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trade_operation.TradeOperation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trade_operation.TradeOperation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeOperation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade_operation.TradeOperation/SendSystemInfo',
            trade__operation__pb2.SystemInfoRequest.SerializeToString,
            trade__operation__pb2.SystemInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRefDataInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade_operation.TradeOperation/SendRefDataInfo',
            trade__operation__pb2.RefDataInfoRequest.SerializeToString,
            trade__operation__pb2.RefDataInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
