# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trade_operation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trade_operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15trade_operation.proto\x12\x0ftrade_operation\"\xe7\x01\n\x11SystemInfoRequest\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x10\n\x08\x63pu_temp\x18\x02 \x01(\x05\x12\x18\n\x10motherboard_temp\x18\x03 \x01(\x05\x12\x13\n\x0b\x65xanic_temp\x18\x04 \x01(\x05\x12\x11\n\thdd_usage\x18\x05 \x01(\x02\x12\x11\n\tram_usage\x18\x06 \x01(\x02\x12\x13\n\x0b\x63lock_drift\x18\x07 \x01(\x02\x12\x17\n\x0fptp_sync_status\x18\x08 \x01(\x08\x12\x13\n\x0bpage_faults\x18\t \x01(\x04\x12\x13\n\x0b\x66\x61n_failure\x18\n \x01(\x08\"%\n\x12SystemInfoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x14\n\x12RefDataInfoRequest\"&\n\x13RefDataInfoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc9\x01\n\x0eTradeOperation\x12Y\n\x0eSendSystemInfo\x12\".trade_operation.SystemInfoRequest\x1a#.trade_operation.SystemInfoResponse\x12\\\n\x0fSendRefDataInfo\x12#.trade_operation.RefDataInfoRequest\x1a$.trade_operation.RefDataInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMINFOREQUEST']._serialized_start=43
  _globals['_SYSTEMINFOREQUEST']._serialized_end=274
  _globals['_SYSTEMINFORESPONSE']._serialized_start=276
  _globals['_SYSTEMINFORESPONSE']._serialized_end=313
  _globals['_REFDATAINFOREQUEST']._serialized_start=315
  _globals['_REFDATAINFOREQUEST']._serialized_end=335
  _globals['_REFDATAINFORESPONSE']._serialized_start=337
  _globals['_REFDATAINFORESPONSE']._serialized_end=375
  _globals['_TRADEOPERATION']._serialized_start=378
  _globals['_TRADEOPERATION']._serialized_end=579
# @@protoc_insertion_point(module_scope)
